#pragma once

// Generated by tools/tile_selector.py. Edit through the selector so the JSON and
// this compile-time header stay in sync.
namespace TileMappings {

inline constexpr const char* BUILDING_SHEET = "";
inline constexpr const char* FENCE_SHEET = "";
inline constexpr const char* BRICK_SHEET = "/tileoverrides/brick_tileset";
inline constexpr const char* ROOF_SHEET = "";
inline constexpr const char* BACKGROUND_SHEET = "";

inline constexpr int BUILDING_FACADE[8] = {5, 6, 8, 18, 21, 31, 32, 34};
inline constexpr int BUILDING_CONNECTED[16] = {14, 48, 43, 44, 66, 74, 69, 44, 1, 8, 4, 44, 14, 14, 14, 44};
inline constexpr int BUILDING_FLOOR[4] = {59, 59, 59, 59};
inline constexpr int FENCE_CONNECTED[16] = {4, 5, 4, 14, 6, 9, 10, 14, 6, 9, 10, 6, 5, 5, 5, 4};
inline constexpr int BRICK_CONNECTED[16] = {6, 6, 6, 16, 6, 17, 15, 0, 5, 5, 0, 6, 6, 6, 6, 6};

// Two roof styles, five vertical bands, three horizontal positions.
inline constexpr int ROOF[2][5][3] = {
    {{0, 1, 2}, {16, 17, 18}, {32, 33, 34}, {48, 49, 50}, {64, 65, 66}},
    {{8, 9, 10}, {24, 25, 26}, {40, 41, 42}, {56, 57, 58}, {72, 73, 74}}
};

inline constexpr int GRASS[5] = {5, 5, 5, 5, 5};
inline constexpr int GRASS_DETAIL[3] = {3, 51, 52};
inline constexpr int DIRT = 39;
inline constexpr int ROAD[2] = {221, 221};
inline constexpr int GRASS_DIRT[16] = {5, 344, 342, 343, 296, 320, 368, 368, 294, 369, 318, 369, 295, 392, 393, -1};

}  // namespace TileMappings
